// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(LevantamentoContext))]
    partial class LevantamentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("API.Models.LevantamentoModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarneVendida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carvao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataLevantamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FranbaconVendido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinguicaVendida")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoCarneDespesa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoCarvao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoFranbaconDespesa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoLinguicaDespesa")
                        .HasColumnType("TEXT");

                    b.Property<int>("QntCarneDespesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QntFranbaconDespesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QntLinguicaDespesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Levantamento");
                });
#pragma warning restore 612, 618
        }
    }
}
